HAPVIDA_CSV_PATH = r"data\RECLAMEAQUI_HAPVIDA.csv"
IBYTE_CSV_PATH = r"data\RECLAMEAQUI_IBYTE.csv"
NAGEM_CSV_PATH = r"data\RECLAMEAQUI_NAGEM.csv"

#Imagens
LOGO_RECLAME_PATH = r"img\logo-reclame-aqui.png"